version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ap2_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:15-alpine
    container_name: ap2_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ap2_redis
    ports:
      - '6379:6379'

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: ap2_payment_service
    depends_on:
      - rabbitmq
      - db
    environment:
      PAYMENT_GRPC_PORT: '50051'
      RABBITMQ_URL: 'amqp://guest:guest@rabbitmq:5672/'
      POSTGRES_URL: 'postgres://postgres:password@db:5432/payments?sslmode=disable'
    ports:
      - '50051:50051'

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: ap2_order_service
    depends_on:
      - payment-service
      - redis
    environment:
      ORDER_HTTP_PORT: '8080'
      ORDER_GRPC_PORT: '50052'
      PAYMENT_GRPC_ADDRESS: 'payment-service:50051'
      ORDER_REDIS_URL: 'redis:6379'
      ORDER_CACHE_TTL: '5m'
    ports:
      - '8080:8080'
      - '50052:50052'

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: ap2_notification_service
    depends_on:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: 'amqp://guest:guest@rabbitmq:5672/'
      RABBITMQ_QUEUE: 'payment.completed'
      NOTIFICATION_REDIS_URL: 'redis:6379'
      PROVIDER_MODE: 'SIMULATED'
      PROVIDER_FAILURE_RATE: '20'
      PROCESSED_TTL: '24h'
      RETRY_MAX_ATTEMPTS: '3'
      RETRY_BASE_DELAY: '2s'
